version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: kanban_user
      POSTGRES_PASSWORD: kanban_pass
      POSTGRES_DB: kanban
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    environment:
      DATABASE_URL: postgresql://kanban_user:kanban_pass@db:5432/kanban
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  db_data:
